### ISSUE TITLE
Doesn't work on Spark 1.6 anymore - NoClassDefFoundError: org/apache/spark/internal/Logging ?

### ISSUE THREAD

**Issue by VictorDusautois** [stefanobaghino/spark-twitter-stream-example#12]
Hi,
Have cloned the latest repo and unable to run it via spark-shell, getting error below:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging

**Comment by stefanobaghino** [comment]
Hi, Victor. You can easily check out a previous commit where it worked.

**Comment by stefanobaghino** [comment]
Maybe `58a7d43` could work for you.
